### ISSUE TITLE
Implementing attachShadow

### ISSUE THREAD

**Issue by hudelgado** [WebReflection/basicHTML#23]
Hi, do you think that is possible to implement the attachShadow method to support the ShadowDOM functionality?
I would like to help with that, but i'm not quite sure of how to do it.
Do you think it is a good contribution? And if so have any ideia about how it could be done?

Thanks
Hugo

**Comment by WebReflection** [comment]
the [method is already there](https://github.com/WebReflection/basicHTML/blob/9c3eee4063cb43e1c67dab9833c7f12681ac0db7/src/Element.js#L97-L105), but it makes little sense to implement something not representable as HTML.

What's your case?

**Comment by hudelgado** [comment]
Humm, ok.
Currently none, i've been experimenting with your project and found it wasn't working as supposed and since i've been working lately with custom elements i thought it could be a good help while i could learn a little bit more.

But thanks anyway.
Cheers
