### ISSUE TITLE
question: should basicHTML mock XMLHttpRequest ?

### ISSUE THREAD

**Issue by douglasduteil** [WebReflection/basicHTML#24]
Hi @WebReflection 

I'm starting using basicHTML as a replacement of jsdom in [my test environment](https://github.com/douglasduteil/jest-environment-basichtml). It seems like there is not XMLHttpRequest implementation in basicHTML. 
Would you welcome a PR to add it ?
Or should I add it in my project as

```js
global.XMLHttpRequest = class {} //sth...
```

**Comment by WebReflection** [comment]
Hi @douglasduteil,
  this project is about the UI part of the DOM, not every W3C API.

Being XHR something rather network related, I don't think basicHTML is the right place to have it.

However, it's deadly simple to bring in [xmlhttprequest](https://www.npmjs.com/package/xmlhttprequest) so I suggest you do that.

The reason I won't add any xhr dependency in here is also that this module is usable to create layouts where the DOM isn't allowed, as in Service Workers (or Workers in general), like [you can see in here](hyperHTML does service worker).

Having unnecessary polyfills that are useless for the Web, would make this module less portable.
