### ISSUE TITLE
Problems with nodeName

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/basicHTML#27]
While testing with basichtml i found that nodeName of the elements are reported with lower-case while the browsers (as far as i know) reports them as uppercase, is that something you can fix?

If there are some browsers that reports them as lower case i may have to update my code then :D

**Comment by WebReflection** [comment]
basicHTML is compatible with everything, not just the browser, and it's camel sensitive on purpose, nothing that will ever change.
