### ISSUE TITLE
canvas.getContext() not working when canvas created with basicHTML.

### ISSUE THREAD

**Issue by Divy123** [WebReflection/basicHTML#32]
I was trying to implement this:
```
var canvas;
    if (options.inBrowser) {
      canvas = document.querySelector(selector);
    }
    else {
      const { Document } = require('basichtml');
      const document = new Document();
      // common accessors
      document.documentElement.innerHTML = `
        <canvas id='image-sequencer-canvas'></canvas>
      `;
      canvas = document.querySelector('#image-sequencer-canvas');
    }
```
and then
```
var gl;
gl = canvas.getContext(names[i], { preserveDrawingBuffer: true });
```
but gl always turns out to be undefined.
Please help.
@WebReflection

**Comment by WebReflection** [comment]
I'm sorry, what are you trying to do with a canvas here?

**Comment by WebReflection** [comment]
Just to clarify, implementing the whole 2d/3d canvas API in here is way beyond the scope of this project.

I might consider exposing some special method you can hook into it for the canvas, but I'll never make `getContext` work in here.

Would that work?

**Comment by WebReflection** [comment]
Since the issue was from last year and there are no answers, I'll close this.

**Comment by WebReflection** [comment]
FYI version 1 has both canvas and image implemented.
See https://github.com/WebReflection/basicHTML#new-in-v1

**Comment by bigopon** [comment]
@WebReflection lol nice job 🎉
