### ISSUE TITLE
Implement NamedNodeMap?

### ISSUE THREAD

**Issue by grommett** [WebReflection/basicHTML#35]
Would you consider a PR implementing [`NamedNodeMap`](https://dom.spec.whatwg.org/#interface-namednodemap) interface in the Element class? Or at least exposing the `item` method?

Currently, the project I'm working in makes a call to `element.attributes.item` and fails when the element is created using basicHTML 😢

**Comment by WebReflection** [comment]
`0.22` has it, but watch out HTMLElement always have a `style` attribute so if you think `length` should be ever 0, that won't likely be the case (it's 1).

However, `.item(0)` works now, so I hope that's enough 👋

**Comment by grommett** [comment]
@WebReflection That's perfect. Thank you!
