### ISSUE TITLE
window.addEventListener is not a function

### ISSUE THREAD

**Issue by Merlin-R** [WebReflection/basicHTML#36]
basicHTML does not define addEventListener or removeEventListener for the window object.
What I tried to do:
```JS
window.addEventListener("some-custom-event", console.log.bind(console));
```
Expected Behavior:
 - Register an event handler that logs "some-custom-event" events to console.

Actual:
‌`TypeError: window.addEventListener is not a function`

**Comment by WebReflection** [comment]
what's the use case?

**Comment by WebReflection** [comment]
Sorry, it was probably a silly question ... the thing is, I likely need to pollute the global context/scope with `add/removeEventListener` since there's no `window` in here.

**Comment by Merlin-R** [comment]
I mainly use basicHTML for unit tests with webcomponents.

I am creating a few webcomponent decorators heavily inspired by StencilJS, one of them being `@Listen`. This method decorator takes a string as an argument, examples being `some-custom-event`, `#inner:change` or `window:keyup` and automatically registers the decorated function as an event handler. For this I need window.addEventListener to add the 'keyup' event listener for example.

Another Example:
```TS
@Component({ renderer: 'hyper', shadow: true })
export class SomePopoverElement extends HTMLElement {
  @Prop({mutable:true})
  width: number;
  @Prop({mutable:true})
  height: number;
  @Listen('window:resize')
  handleWindowResize(ev: Event) {
    // Recalculate width / height here
  }

  render(html) {
    return html`<div width=${this.width} height=${this.height}><slot /></div>`;
  }
}
```

For now as a workaround I create a random div in a setup.ts file and use its add-/removeEventHandler, dispatchEvent functions bound to the div element just so my code is testable.

As you can probably tell, this isn't an ideal solution.
