### ISSUE TITLE
Add support for replaceWith()

### ISSUE THREAD

**Issue by nhoizey** [WebReflection/basicHTML#45]
This is the doc [from MDN](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith):

> The ChildNode.replaceWith() method replaces this ChildNode in the children list of its parent with a set of Node or DOMString objects. DOMString objects are inserted as equivalent Text nodes.

There is a polyfill in MDN page.

In the meantime, it should be possible to use `replaceChild()` on the parent node.

**Comment by WebReflection** [comment]
just to make it clear, I won't implement any polyfill here, 'cause this project focuses on real-world use cases, not on 100% specs compliance, accordingly, would this work for you?

```js
replaceWith(node) {
  this.parentNode.replaceChild(node, this);
}
```

'cause that's usually all I use `replaceWith` for, there's `remove()` for removing, and other methods to do other things. I hope this sounds reasonable.

**Comment by nhoizey** [comment]
This is perfectly enough, thanks a lot!

**Comment by WebReflection** [comment]
this is not in yet

**Comment by nhoizey** [comment]
Sorry, I thought you were suggesting me to do it in my own code.

**Comment by WebReflection** [comment]
so, `2.2.0` implements https://dom.spec.whatwg.org/#interface-childnode in a simplified way, that should solve `replaceWith`, `before`, `after`, and `remove` cases.

**Comment by nhoizey** [comment]
Wow, that's fast, thanks! 👍
