### ISSUE TITLE
Text and Comment classes should implement `ChildNode` interface?

### ISSUE THREAD

**Issue by coreyfarrell** [WebReflection/basicHTML#54]
I found this while using basichtml for some testing.  Minimal failing test case:
```js
const assert = require('assert');
const {body} = require('basichtml').init().document;

body.innerHTML = 'Text<!--comment-->';
[...body.childNodes].forEach(node => node.remove());
assert.strictEqual(body.innerHTML, '');
```

This throws `TypeError: node.remove is not a function` where I expected the test to silently succeed.  I realize the whatwg standard doesn't show Text or Comment implementing ChildNode but https://developer.mozilla.org/en-US/docs/Web/API/CharacterData#Browser_compatibility shows that CharacterData implements ChildNode in most browsers.

**Comment by WebReflection** [comment]
yes, it looks like by standards these should be allowed in CharacterData:
https://dom.spec.whatwg.org/#childnode

**Comment by coreyfarrell** [comment]
I had asked about the spec vs MDN docs in the `#whatwg` IRC channel and was just told that it was listed under childnode (somehow I didn't see this when reading the specs).

**Comment by WebReflection** [comment]
ChracterData includes ChildNodes

![Screenshot from 2020-11-22 14-24-56](https://user-images.githubusercontent.com/85749/99905018-84554d00-2cce-11eb-9b5a-f70937915527.png)

**Comment by WebReflection** [comment]
It's in the patch 👋
