### ISSUE TITLE
Broken inline CSS custom properties

### ISSUE THREAD

**Issue by nhoizey** [WebReflection/basicHTML#56]
Hi, when I take the example "Good old way to init with basic selectors" from the README and add an inline custom property to the `body` element (with ` style="--foo: bar"`), it is transformed in the output, with the two dashes transformed into one only.

Script:

```javascript
const { Document } = require("basichtml");

const document = new Document();

// attributes
document.documentElement.setAttribute("lang", "en");

// common accessors
document.documentElement.innerHTML = `
  <head></head>
  <body style="--foo: bar"></body>
`;
document.body.textContent = "Hello basicHTML";

// basic querySelector / querySelectorAll
document
  .querySelector("head")
  .appendChild(document.createElement("title")).textContent = "HTML on NodeJS";

// toString() necessary to read, it's a Buffer
console.log(document.toString());
```

Output:

```html
<!DOCTYPE html><html lang="en">
  <head><title>HTML on NodeJS</title></head>
  <body style="-foo:bar;">Hello basicHTML</body>
</html>
```

`style="--foo: bar"` is transformed into `style="-foo:bar;"`.

**Comment by WebReflection** [comment]
Bummer … have you tried or hear about LinkeDOM? Is the only thing I’m using these days, close to deprecate this module, as it’s too narrow with its cope, and it fails at everything

**Comment by WebReflection** [comment]
P.S. it’s literally the first part of the README

**Comment by nhoizey** [comment]
Yes, I have heard about LinkeDOM (the day you released it!), I really want to use it instead of BasicHTML.

But I have multiple sites using BasicHTML, and npm packages depending on it used by many people, so I will unfortunately not be able to migrate right now. 😭

**Comment by nhoizey** [comment]
I should have said that I fully understand if you don't want to work on BasicHTML anymore, as deprecation is indeed obviously stated in the README. 👍

It looks like LinkeDOM will anyway be easier to use than BasicHTML, so I have to plan the migration ASAP.

**Comment by WebReflection** [comment]
I should probably put a copy/paste code here or there to explain how to have same results just better and faster via LinkeDOM

**Comment by WebReflection** [comment]
P.S. PR welcome, as I’m having zero times these days to deal with projects pre announced as deprecated. This should be relatively easy, but time is against me.

**Comment by nhoizey** [comment]
> I should probably put a copy/paste code here or there to explain how to have same results just better and faster via LinkeDOM

It would be awesome.

> PR welcome, as I’m having zero time these days to deal with projects pre announced as deprecated. This should be relatively easy, but time is against me.

I will try to move to LinkeDOM first, but if I'm not able to do so, I'll try to find a fix for BasicHTML. But last time I checked the code, I didn't understand much… 🙁

**Comment by WebReflection** [comment]
All right, I think I've fixed it.

**Comment by nhoizey** [comment]
@WebReflection I'll test in my code today, thanks a lot! 👍

**Comment by WebReflection** [comment]
I broke the build 🥳

... but now it should be fine.

**Comment by nhoizey** [comment]
I can confirm that the issue is fixed on my side, thanks A LOT for taking the time to fix it! 🙏
